# Site Info
title: Codinfox Lanyon
tagline: 'Life is short. Be grateful'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
baseurl:
url: https://dingyunxing.github.io
logo: '/public/logo.png'

# Site configurations
gems: [jekyll-paginate]
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty


version: 1.0.0

# About/contact
author:
  name: James Ding
  description: A passionate <strong>code lover</strong>, learning to be a giant.
  # gravatar: 752f6d4e5ac765d0f82f54fc853af91b # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/yunxing-ding-69949abb/
    github:    https://github.com/dingyunxing
    # facebook:  <hide>
    twitter:   https://twitter.com/Yunxing_Ding
    weibo:     https://weibo.com/dingyunxinghengeili/home
    email:     dingyunxing@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/dingyunxing/dingyunxing.github.io'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="https://store.kakaofriends.com/index/today">Kakao Friends</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'dingyunxing' # leave blank if you don't want disqus

